### ISSUE TITLE
Inventory#dropAll overwrite may break mods' expectations

### ISSUE THREAD

**Issue by Pyrofab** [CerulanLumina/better-graves#1]
The [`dropAll` Overwrite](https://github.com/CerulanLumina/better-graves/blob/master/src/main/java/bettergraves/mixin/MixinPlayerInventory.java#L27-L33) will affect the behaviour of any mod that calls the method directly. It would probably be better to leave the original method intact and redirect the call in `PlayerEntity#dropInventory` instead.

**Comment by LuminaSapphira** [comment]
Thanks for this~

**Comment by LuminaSapphira** [comment]
Could you check to see if I used redirect appropriately (in a way that won't break other mods' expectations)? Thanks~~

**Comment by Pyrofab** [comment]
Looks fine ! But I would recommend using `At#target` instead of `At#ordinal` to select the redirected method call. It would be less likely to break, and would make the code clearer.

**Comment by LuminaSapphira** [comment]
Moved to using target, re-open if there's anything else I should change here
