### ISSUE TITLE
Dying next to fence causes grave not to spawn

### ISSUE THREAD

**Issue by KydZombie** [CerulanLumina/better-graves#13]
If you die while standing inside of a fence, your grave will not spawn, and you will lose all items you had

**Comment by LuminaSapphira** [comment]
Cannot confirm, please supply additional information 
![image](https://user-images.githubusercontent.com/1103450/91577065-32429c80-e916-11ea-9537-58ac2100012a.png)

**Comment by KydZombie** [comment]
I was in an abandoned mineshaft, so there was no air block above the fence post

**Comment by LuminaSapphira** [comment]
I see, it probably ascended to the surface, or in some cave between the fence and the surface. I'll chalk this one up to a random edge case not accounted for in the placement logic.

I'll see about improving the placement logic.
