### ISSUE TITLE
Crash when placing grave via a death

### ISSUE THREAD

**Issue by furtabs** [CerulanLumina/better-graves#4]
[crash-2020-02-12_21.49.36-server.txt](https://github.com/CerulanLumina/better-graves/files/4196254/crash-2020-02-12_21.49.36-server.txt)

**Comment by LuminaSapphira** [comment]
Does this occur with only Better Graves and Fabric API installed? If not, is there a certain (preferably small) subset of mods that it occurs with?

**Comment by furtabs** [comment]
Havent tested i would assumb not because it would of been brought up by now

**Comment by furtabs** [comment]
it isnt your mod
