### ISSUE TITLE
Crash when you Die when Gamerule spawnRadius = 0

### ISSUE THREAD

**Issue by furtabs** [CerulanLumina/better-graves#7]
https://pastebin.com/r6Ujqgb4

**Comment by LuminaSapphira** [comment]
Unable to reproduce under spawnRadius = 0, however there does appear to be an issue involving the name rendering

**Comment by LuminaSapphira** [comment]
Added safeguards to avoid crashing, does not, however, fix the issue (simply refuses to render). LMK how it goes.

0.2.1-beta.2 available on curseforge
